version: '3.4'
services:
  injectiondb:
    image: postgres:15.4
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ~/ws/olihock/ithoc-training/cyber-security/injectiondb-volume:/var/lib/postgresql/data
